### ISSUE TITLE
[NSML] 제출 포맷 관련 문의

### ISSUE THREAD

**Issue by msh9184** [hunminjeongeum-competition-final-2021/speaker-recognition#1]
# 주제
- 제출 포맷 관련 문의

# 상황 (자세히 작성해주시면 좋습니다.)

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)

안녕하세요, 본선 제출 포맷 관련 질문드립니다.

예선에서 남겨주신 코맨트에 따르면, eer 측정을 위한 `pred` 값은 0~1 사이 확률 값 (혹은 정답으로 예측한 binary) 형태로 구성되었던 것 같습니다.

혹시 본선 eer 계산 방식도 `pred` 포맷을 확률 형태로만 제출하도록 되어있는지 문의 드립니다.
(두 입력에 대한 distance 혹은 llr과 같은 metric도 사용 가능할지 궁금하여 질문 드립니다.)

```python
def infer(test_path, **kwparser):
   ...
    for i in left_paths:
        test_left.append(get_spectrogram_(i))
    for i in right_paths:
        test_right.append(get_spectrogram_(i))
    pred = np.argmax(model.predict([np.array(test_left), np.array(test_right)]), axis = 1)
    prob = [1]*len(pred)

    # DONOTCHANGE: They are reserved for nsml
    # 리턴 결과는 [(확률, 0 or 1)] 의 형태로 보내야만 리더보드에 올릴 수 있습니다. 
    # 리더보드 결과에 확률의 값은 영향을 미치지 않습니다
    return list(zip(prob, pred))
```

# 기타 문의 사항

**Comment by DaconHoneyBee** [comment]
@msh9184 안녕하세요.
본선의 제출 포맷 및 평가 방식은 예선과 동일합니다.
스코어는 eer로 평가되며, pred 값은 0~1 사이 확률 값 (혹은 정답으로 예측한 binary) 형태로 제출해주시면 됩니다.
감사합니다.
