### ISSUE TITLE
[NSML] Submit 시 예측 결과 불러오기 오류

### ISSUE THREAD

**Issue by JinsolPark** [hunminjeongeum-competition-final-2021/speaker-recognition#10]
# 주제
- 모델 submit 시 예측 결과 불러오기 오류

# 상황 (자세히 작성해주시면 좋습니다.)
- 어제부터 모델 submit 시 Error: Fail to get prediction result: ~ 발생합니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 사용자 세션 정보: nia3037
- Session ID: nia3037/final_speaker/78
- 팀명: Bibimbap
- CLI 에러 (CLI 에러가 아닌 경우 제거)
   ```shell
   # Error: Fail to get prediction result:
   $ test
   ```
![image](https://user-images.githubusercontent.com/87758046/141123120-2cca292d-2201-41c9-85ff-4968077cc5be.png)

- 웹 UI 에러 이미지
 // 이곳에 에러 이미지를 추가해주세요

# 기타 문의 사항
-

**Comment by bluebrush** [comment]
@JinsolPark 님, 
`nsml submit -t`로 먼저 확인 진행부탁드립니다. 

`nsml submit -t nia3037/final_speaker/77 0`  진행하시면 될 것 같습니다.

**Comment by JinsolPark** [comment]
저 방법으로 해결되지는 않았습니다만 현재는 다시 잘 돌아갑니다. 감사합니다.
