### ISSUE TITLE
[NSML] docker image pytorch 버전 관련

### ISSUE THREAD

**Issue by msh9184** [hunminjeongeum-competition-final-2021/speaker-recognition#13]
# 주제
- docker container image pytorch 버전 관련

# 상황 (자세히 작성해주시면 좋습니다.)
- pytorch 버전에 따라 성능 차이가 크게 발생하는 것을 이제 확인하여 문의 드립니다.
- 현재 설치된 버전은 1.10.0버전으로 확인 되는데, 1.6.0 혹은 1.7.0 버전으로 구동이 가능할지 문의 드립니다.
- 너무 늦게 문의 드려 죄송합니다. 혹시나 하는 마음으로 문의 드립니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)

- 웹 UI 에러 이미지

# 기타 문의 사항
-

**Comment by nsmluser** [comment]
@DaconHoneyBee 님, 혹시, 적당한 docker image link 선택하여 알려주실 수 있을지요?

**Comment by DaconHoneyBee** [comment]
@nsmluser  @msh9184 안녕하세요.
원하시는 특정 환경으로 도커 이미지를 빌드해서 사용하실 수 있습니다.
[도커 이미지 빌드 가이드](https://github.com/hunminjeongeum-korean-competition-2021/docs/blob/main/DockerImage.md)를 참고해주시기 바랍니다.
감사합니다.

**Comment by msh9184** [comment]
@nsmluser @DaconHoneyBee 네! 확인 감사드립니다!
