### ISSUE TITLE
[Dataset] data leakage 판정 범위 문의

### ISSUE THREAD

**Issue by Gabibing** [hunminjeongeum-competition-final-2021/speaker-recognition#14]
# 주제
- data leakage 판정 범위 문의

# 상황 (자세히 작성해주시면 좋습니다.)
- submit 시 평가 데이터에 모두 0, 혹은 모두 1 을 넣어서 test 셋의 분포를 인지한 후 코드를 작성하는 경우 leakage 인가요?
- 개인적으론 leakage 같긴 한데, 현재 NSML 상에서는 확인 가능하게 되어있어서 문의 드립니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 현재 improve 가능한 마지막 시점인데 data leakage 판정인지 애매해서 문의드립니다.

**Comment by DaconHoneyBee** [comment]
@Gabibing 안녕하세요.
문의 주신 내용은 Data Leakage에 해당합니다. 
코드 검증 과정에서 Data Leakage를 했다고 판단될 시 불이익을 받을 수 있으니 주의 부탁드립니다. 
감사합니다.
