### ISSUE TITLE
[NSML] Not enough resources for your request 오류 관련

### ISSUE THREAD

**Issue by msh9184** [hunminjeongeum-competition-final-2021/speaker-recognition#3]
# 주제
- Not enough resources for your request 오류 관련

# 상황 (자세히 작성해주시면 좋습니다.)
- 최초 1회 시도 이후 자원 할당이 되고 있지 않습니다. 확인해 주심 감사드리겠습니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 사용자 세션 정보: -
- Session ID: -
- 팀명: shmun

- 웹 UI 에러 이미지
![그림1](https://user-images.githubusercontent.com/33674982/139699708-a33ac686-099a-40a5-bd4b-280ab5abb3a1.png)

# 기타 문의 사항
-

**Comment by msh9184** [comment]
해결 되었습니다 :)

**Comment by gusals6804** [comment]
저도 동일한 이슈입니다.  하지만 다시 실행하면 또 같은 에러가 발생하지 않나요? 한참을 기다려야 다시 할당 받아서 실행이 되는 것 같습니다.

**Comment by msh9184** [comment]
@gusals6804 ~~이번엔 프로그램 종료(에러 등의 이유로) 후 직접 세션을 삭제 해 주셔야 하는 것 같아보입니다. (nsml rm -f [niaxxxx/final_speaker/xx)
그리고 잠시 기다렸다가 실행시키니 되는 것 같아보이네요!~~
-> 세션 삭제랑 관계없이 @gusals6804 님 말처럼 한참 기다린 후 실행해야 하는 것 같네요.

**Comment by bluebrush** [comment]
@msh9184 님, 
dataset 이 변경(신규 + 사이즈 증가)되면서, 최초 실행되는 노드에는 시간이 소요될 것 같습니다.

**Comment by msh9184** [comment]
@bluebrush 넵! 확인 감사드립니다.

**Comment by msh9184** [comment]
@bluebrush 님, 혹시 리소스 할당 관련해서 검토 한번만 부탁드려도 괜찮을지요?
이상할 정도로 세션 실행이 불규칙한 것 같아 문의 드립니다. 가끔은 1시간이 넘게 기다려도 실행이 불가합니다.
확인해 주시면 감사드리겠습니다!

**Comment by K-BS** [comment]
저희도 동일한 문제를 겪고 있습니다. 현재 3시간 이상 기다려도 실행이 불가합니다 ㅜㅜ!

![image](https://user-images.githubusercontent.com/74411831/139637305-f53edb3b-da33-4707-b5fe-bf509b17696e.png)

**Comment by bluebrush** [comment]
@K-BS 님, @msh9184 님, 
이슈 함께 해결되었습니다. 
이후 자원 이슈가 있으면 다시 알려주세요.
