### ISSUE TITLE
[NSML] 컴퓨팅 리소스 문제

### ISSUE THREAD

**Issue by Gabibing** [hunminjeongeum-competition-final-2021/speaker-recognition#5]
# 주제
- 컴퓨팅 리소스가 부족해서 job이 종료됐다는 메시지가 뜹니다.

# 상황 (자세히 작성해주시면 좋습니다.)
- 오랜 시간동안 세션 생성이 안 됩니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
![image](https://user-images.githubusercontent.com/25878266/139637539-38a44738-4224-4d8d-8f48-af8fce6d7ded.png)

**Comment by bluebrush** [comment]
`nsml run` 명령 라인과
`nsml ps` 명령 결과 확인 가능할까요?

**Comment by Gabibing** [comment]
> `nsml run` 명령 라인과 `nsml ps` 명령 결과 확인 가능할까요?

=> nsml run -d final_speaker -e main.py -a '--epochs 50'
time="2021/11/01 16:45:06.950" level=info msg=".nsmlignore check - start"
time="2021/11/01 16:45:06.980" level=info msg=".nsmlignore check - done"
time="2021/11/01 16:45:07.024" level=info msg="file integrity check - start"
time="2021/11/01 16:45:07.030" level=info msg="file integrity check - done"
time="2021/11/01 16:45:07.036" level=info msg="DockerFile 363 B - start"
time="2021/11/01 16:45:07.037" level=info msg="DockerFile 363 B - done (1/4 25.00%) (363 B/22 KiB 1.61%)"
time="2021/11/01 16:45:07.039" level=info msg="main.py 21 KiB - start"
time="2021/11/01 16:45:07.040" level=info msg="main.py 21 KiB - done (2/4 50.00%) (22 KiB/22 KiB 98.86%)"
time="2021/11/01 16:45:07.042" level=info msg="requirements.txt 88 B - start"
time="2021/11/01 16:45:07.043" level=info msg="requirements.txt 88 B - done (3/4 75.00%) (22 KiB/22 KiB 99.25%)"
time="2021/11/01 16:45:07.045" level=info msg="setup.py 169 B - start"
time="2021/11/01 16:45:07.046" level=info msg="setup.py 169 B - done (4/4 100.00%) (22 KiB/22 KiB 100.00%)"
...Rejected: not enough resources for your request
Since cluster does not have enough computing resources, job has been aborted. Please retry later
Error: No machine available that meets ALL your request such as CPU, RAM, Disk, GPU or its driver version
time="2021/11/01 16:39:55.831" level=fatal msg="Internal server error"
=> nsml ps
Name    Created    Args    Status    Summary    Description    # of Models    Size    Type
(아무것도 안 뜹니다)

**Comment by bluebrush** [comment]
@Gabibing 님, 불편을 드려서 죄송합니다. 
리소스 문제 해결되었습니다.

**Comment by Gabibing** [comment]
@bluebrush 감사합니다!
