### ISSUE TITLE
[Dataset] label 대/소문자 구분 관련 문의

### ISSUE THREAD

**Issue by msh9184** [hunminjeongeum-competition-final-2021/speaker-recognition#7]
# 주제
- label 대/소문자 구분 관련 문의

# 상황 (자세히 작성해주시면 좋습니다.)
- 

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 안녕하세요, 화자 라벨의 대/소문자가 구분이 되는지 문의 드립니다. 
- 예를 들면 [S000013_1, s000013_1] 의 경우 다른 화자로 간주 되는 것인지 같은 화자인지 (혹은 이러한 구성의 라벨은 존재 하지 않는지) 질문 드립니다.

# 기타 문의 사항
-

**Comment by dacon-murdoch** [comment]
안녕하세요 :)

우선 대문자와 소문자는 무조건 다른 화자로 간주되며 말씀하신 구성의 라벨은 존재하지 않습니다.

감사합니다.

**Comment by msh9184** [comment]
넵! 회신 감사드립니다!
