### ISSUE TITLE
[NSML] Ranking에서 팀이 아닌 아이디가 포함되어있습니다

### ISSUE THREAD

**Issue by Gabibing** [hunminjeongeum-competition-final-2021/speaker-recognition#8]
# 주제
- Ranking에서 팀이 아닌 아이디가 포함되어있습니다.

# 상황 (자세히 작성해주시면 좋습니다.)
-  nsml 내 Ranking을 보면 저와 nsmluser 계정이 같은 팀으로 나옵니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- Session ID: nia3028
- 팀명: 웨이브덱
![image](https://user-images.githubusercontent.com/25878266/140094105-b42ee2c6-7023-4b92-a926-61aa7a7e7a39.png)

**Comment by bluebrush** [comment]
@Gabibing 님, 
문의사항 확인 용으로 NSML팀에서 사용하는 내부 계정입니다. 안심하셔도 됩니다. 곧 빠질 예정입니다.
