### ISSUE TITLE
[대회 진행 관련 문의] 코드 license 관련 문의

### ISSUE THREAD

**Issue by Gabibing** [hunminjeongeum-competition-final-2021/speaker-recognition#9]
# 주제
- 코드 license 관련 문의

# 상황 (자세히 작성해주시면 좋습니다.)
- 안녕하세요. 저는 이번 대회에 참가하면서 모델과 loss를 직접 개발하고 있는데요.
- 대회 종료 후, 코드의 license나 저작권 관련 조항을 인지하지 못하고 있어서 문의드립니다.

**Comment by DaconHoneyBee** [comment]
@Gabibing 안녕하세요.
대회 종료 후 코드의 license 및 저작권은 모두 참가자 본인에게 있습니다.
감사합니다.

**Comment by DaconHoneyBee** [comment]
@Gabibing 안녕하세요.
대회 종료 후 코드의 license 및 저작권은 참가자 본인에게 있습니다.
감사합니다.
